import std/[os, strutils]

import clay_board_style_system/input/events

const
  generatedNotice = "# Generated by tools/generate_events.nim. Do not edit.\n"
  generatedRustNotice = "// Generated by tools/generate_events.nim. Do not edit.\n"
  cBeginMarker = "/* CBSS_GENERATED_EVENT_KINDS_BEGIN */"
  cEndMarker = "/* CBSS_GENERATED_EVENT_KINDS_END */"

proc cEventName(kind: InputEventKind): string =
  let source = ($kind)[3 .. ^1]
  for index, character in source:
    if index > 0 and character.isUpperAscii and source[index - 1].isLowerAscii:
      result.add('_')
    result.add(character.toUpperAscii)

proc generatedSlots(templateName: string; assignment: bool): string =
  result = generatedNotice
  for kind in InputEventKind:
    let definition = kind.eventDefinition
    for index in 0 ..< int(definition.publicNameCount):
      let publicName = definition.publicNames[index]
      let symbol = if assignment: "`" & publicName & "=`" else: publicName
      result.add(templateName & "(" & symbol & ", " & $kind & ")\n")

proc generatedCEventKinds(): string =
  result = cBeginMarker & "\n"
  result.add("typedef enum CbssEventKind {\n")
  for kind in InputEventKind:
    let suffix = if kind == high(InputEventKind): "" else: ","
    result.add(
      "  CBSS_EVENT_" & cEventName(kind) & " = " &
      $kind.eventDefinition.abiCode & suffix & "\n"
    )
  result.add("} CbssEventKind;\n")
  result.add(cEndMarker)

proc generatedRustEventKinds(): string =
  result = generatedRustNotice & "\n"
  result.add("#[repr(transparent)]\n")
  result.add("#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\n")
  result.add("pub struct EventKind(u32);\n\n")
  result.add("impl EventKind {\n")
  for kind in InputEventKind:
    result.add("    pub const " & cEventName(kind) & ": Self = Self(" &
      $kind.eventDefinition.abiCode & ");\n")
  result.add("\n    pub const fn code(self) -> u32 {\n")
  result.add("        self.0\n")
  result.add("    }\n")
  result.add("\n    pub const fn from_code(code: u32) -> Self {\n")
  result.add("        Self(code)\n")
  result.add("    }\n")
  result.add("}\n")

proc updateGeneratedFile(path, expected: string; checkOnly: bool): bool =
  let current = if fileExists(path): readFile(path) else: ""
  if current == expected:
    return true
  if checkOnly:
    stderr.writeLine("generated event surface is stale: " & path)
    return false
  writeFile(path, expected)
  true

proc updateCHeader(path: string; checkOnly: bool): bool =
  let current = readFile(path)
  let beginAt = current.find(cBeginMarker)
  let endAt = current.find(cEndMarker)
  if beginAt < 0 or endAt < beginAt:
    stderr.writeLine("generated event markers are missing from " & path)
    return false
  let afterEnd = endAt + cEndMarker.len
  let expected = current[0 ..< beginAt] & generatedCEventKinds() &
    current[afterEnd .. ^1]
  if expected == current:
    return true
  if checkOnly:
    stderr.writeLine("generated C event declarations are stale: " & path)
    return false
  writeFile(path, expected)
  true

proc main() =
  var checkOnly = false
  for argument in commandLineParams():
    case argument
    of "--check":
      checkOnly = true
    else:
      stderr.writeLine("Usage: generate_events [--check]")
      quit(QuitFailure)

  let root = currentSourcePath().parentDir().parentDir()
  let generated = root / "src" / "clay_board_style_system" / "generated"
  var valid = true
  valid = updateGeneratedFile(
    generated / "event_registry_slots.nim",
    generatedSlots("registerEventSlot", false),
    checkOnly
  ) and valid
  valid = updateGeneratedFile(
    generated / "node_event_slots.nim",
    generatedSlots("handleEventSlot", true),
    checkOnly
  ) and valid
  valid = updateGeneratedFile(
    generated / "component_event_slots.nim",
    generatedSlots("componentEventSlot", true),
    checkOnly
  ) and valid
  valid = updateGeneratedFile(
    root / "drivers" / "rust" / "src" / "generated" / "events.rs",
    generatedRustEventKinds(),
    checkOnly
  ) and valid
  valid = updateCHeader(root / "include" / "cbss.h", checkOnly) and valid

  if not valid:
    quit(QuitFailure)

when isMainModule:
  main()
