import std/[json, os, sets, strutils]

type
  Capability = object
    id: uint32
    symbol: string
    name: string
    version: uint32
    sinceAbi: uint32

  DriverContract = object
    engineAbiVersion: uint32
    driverContractVersion: uint32
    capabilities: seq[Capability]

const
  generatedNotice = "# Generated by tools/generate_driver_contract.nim. Do not edit.\n"
  cBeginMarker = "/* CBSS_GENERATED_DRIVER_CONTRACT_BEGIN */"
  cEndMarker = "/* CBSS_GENERATED_DRIVER_CONTRACT_END */"

proc uint32Field(node: JsonNode; field: string): uint32 =
  if not node.hasKey(field) or node[field].kind != JInt:
    raise newException(ValueError, "expected integer field: " & field)
  let value = node[field].getBiggestInt()
  if value < 0 or value > BiggestInt(high(uint32)):
    raise newException(ValueError, "uint32 field is out of range: " & field)
  uint32(value)

proc validSymbol(value: string): bool =
  if value.len == 0:
    return false
  for character in value:
    if not (character in {'A' .. 'Z', '0' .. '9', '_'}):
      return false
  true

proc validName(value: string): bool =
  if value.len == 0 or not value[0].isLowerAscii:
    return false
  for character in value:
    if not (character.isLowerAscii or character.isDigit or
        character in {'.', '-'}):
      return false
  true

proc loadContract(path: string): DriverContract =
  let root = parseFile(path)
  if root.uint32Field("schema_version") != 1'u32:
    raise newException(ValueError, "unsupported driver contract schema")
  result.engineAbiVersion = root.uint32Field("engine_abi_version")
  result.driverContractVersion = root.uint32Field("driver_contract_version")
  if not root.hasKey("capabilities") or root["capabilities"].kind != JArray:
    raise newException(ValueError, "capabilities must be an array")

  var ids = initHashSet[uint32]()
  var symbols = initHashSet[string]()
  var names = initHashSet[string]()
  var previousId = 0'u32
  for item in root["capabilities"]:
    if item.kind != JObject:
      raise newException(ValueError, "capability must be an object")
    let capability = Capability(
      id: item.uint32Field("id"),
      symbol: item{"symbol"}.getStr(),
      name: item{"name"}.getStr(),
      version: item.uint32Field("version"),
      sinceAbi: item.uint32Field("since_abi")
    )
    if capability.id == 0 or capability.id <= previousId:
      raise newException(ValueError, "capability ids must be positive and ordered")
    if capability.version == 0:
      raise newException(ValueError, "capability version must be positive")
    if capability.sinceAbi > result.engineAbiVersion:
      raise newException(ValueError, "capability requires a future engine ABI")
    if not capability.symbol.validSymbol:
      raise newException(ValueError, "invalid capability symbol: " & capability.symbol)
    if not capability.name.validName:
      raise newException(ValueError, "invalid capability name: " & capability.name)
    if capability.id in ids or capability.symbol in symbols or
        capability.name in names:
      raise newException(ValueError, "duplicate capability identity")
    ids.incl(capability.id)
    symbols.incl(capability.symbol)
    names.incl(capability.name)
    result.capabilities.add(capability)
    previousId = capability.id

  if result.capabilities.len == 0:
    raise newException(ValueError, "at least one capability is required")

proc hex32(value: uint32): string =
  "0x" & value.toHex(8)

proc nimSymbol(value: string): string =
  var uppercaseNext = true
  for character in value:
    if character == '_':
      uppercaseNext = true
    elif uppercaseNext:
      result.add(character.toUpperAscii)
      uppercaseNext = false
    else:
      result.add(character.toLowerAscii)

proc generatedNim(contract: DriverContract): string =
  result = generatedNotice
  result.add("\n")
  result.add("type\n")
  result.add("  CbssCapabilityInfoC* {.bycopy.} = object\n")
  result.add("    id*, version*, sinceAbi*, flags*, nameBytes*: uint32\n\n")
  result.add("  CbssCapabilityDefinition* = tuple[\n")
  result.add("    id: uint32, version: uint32, sinceAbi: uint32, name: string\n")
  result.add("  ]\n\n")
  result.add("const\n")
  result.add("  CbssAbiVersion* = " & contract.engineAbiVersion.hex32 & "'u32\n")
  result.add("  CbssDriverContractVersion* = " &
    contract.driverContractVersion.hex32 & "'u32\n")
  result.add("  CbssCapabilityAvailable* = 1'u32 shl 0\n")
  for capability in contract.capabilities:
    result.add("  CbssCapability" & capability.symbol.nimSymbol &
      "* = " & $capability.id & "'u32\n")
  result.add("  CbssCapabilities*: array[" & $contract.capabilities.len &
    ", CbssCapabilityDefinition] = [\n")
  for index, capability in contract.capabilities:
    let suffix = if index == contract.capabilities.high: "" else: ","
    result.add("    (id: " & $capability.id & "'u32, version: " &
      $capability.version & "'u32, sinceAbi: " & capability.sinceAbi.hex32 &
      "'u32, name: \"" & capability.name & "\")" & suffix & "\n")
  result.add("  ]\n")

proc generatedC(contract: DriverContract): string =
  result = cBeginMarker & "\n"
  result.add("#define CBSS_ABI_VERSION " & contract.engineAbiVersion.hex32 & "u\n")
  result.add("#define CBSS_DRIVER_CONTRACT_VERSION " &
    contract.driverContractVersion.hex32 & "u\n\n")
  result.add("typedef enum CbssCapabilityId {\n")
  for index, capability in contract.capabilities:
    let suffix = if index == contract.capabilities.high: "" else: ","
    result.add("  CBSS_CAPABILITY_" & capability.symbol & " = " &
      $capability.id & "u" & suffix & "\n")
  result.add("} CbssCapabilityId;\n\n")
  result.add("enum {\n  CBSS_CAPABILITY_AVAILABLE = 1u << 0\n};\n\n")
  result.add("typedef struct CbssCapabilityInfo {\n")
  result.add("  uint32_t id;\n  uint32_t version;\n  uint32_t since_abi;\n")
  result.add("  uint32_t flags;\n  uint32_t name_bytes;\n")
  result.add("} CbssCapabilityInfo;\n")
  result.add(cEndMarker)

proc updateFile(path, expected, description: string; checkOnly: bool): bool =
  let current = if fileExists(path): readFile(path) else: ""
  if current == expected:
    return true
  if checkOnly:
    stderr.writeLine(description & " is stale: " & path)
    return false
  writeFile(path, expected)
  true

proc updateCHeader(
    path: string;
    contract: DriverContract;
    checkOnly: bool
): bool =
  let current = readFile(path)
  let beginAt = current.find(cBeginMarker)
  let endAt = current.find(cEndMarker)
  if beginAt < 0 or endAt < beginAt:
    stderr.writeLine("generated driver contract markers are missing from " & path)
    return false
  let afterEnd = endAt + cEndMarker.len
  let expected = current[0 ..< beginAt] & contract.generatedC &
    current[afterEnd .. ^1]
  if expected == current:
    return true
  if checkOnly:
    stderr.writeLine("generated C driver contract is stale: " & path)
    return false
  writeFile(path, expected)
  true

proc main() =
  var checkOnly = false
  for argument in commandLineParams():
    case argument
    of "--check":
      checkOnly = true
    else:
      stderr.writeLine("Usage: generate_driver_contract [--check]")
      quit(QuitFailure)

  let root = currentSourcePath().parentDir().parentDir()
  try:
    let contract = loadContract(root / "schema" / "craft_driver_contract.json")
    var valid = true
    valid = updateFile(
      root / "src" / "clay_board_style_system" / "generated" /
        "craft_driver_contract.nim",
      contract.generatedNim,
      "generated Nim driver contract",
      checkOnly
    ) and valid
    valid = updateCHeader(root / "include" / "cbss.h", contract, checkOnly) and valid
    if not valid:
      quit(QuitFailure)
  except CatchableError as error:
    stderr.writeLine("driver contract generation failed: " & error.msg)
    quit(QuitFailure)

when isMainModule:
  main()
